### ISSUE TITLE
Inconsistent hyperparameters reported in the paper and configuration files

### ISSUE THREAD

**Issue by jingsenzhu** [snap-research/NeROIC#20]
I found some hyperparameters in configuration files inconsistent with those reported in the original paper. For example, lambda_tr is 1 in config while 0.01 in the original paper. Which one should I refer to?

**Comment by zfkuang** [comment]
Since our two stages use different blending methods for the transient color, the lambda_tr is also set to different values. In our paper, lambda_tr is set to 0.01 for the geometry stage and to 1 for the rendering stage, which is consistent with our configs. If there's any other differences between the configs and the paper, please let us know (and try config first).
