### ISSUE TITLE
Relighting problems

### ISSUE THREAD

**Issue by Menpinland** [snap-research/NeROIC#22]
Thanks to the authors for your contributions. Here I have some questions about relighting:
1. When I run `test_relighting.py` using milkbox sample with an outdoor image (download from google), but the relighting results seem a littie bad. After checking the code, I found that the relighting results were highly dependent on the setting of `args.test_env_maxthres`. I am curious about how to choose the env image and set the `args.test_env_maxthres` to achieve the better relighting results?

**The outdoor image we used while tesing the milkbox sample:**
![outdoor](https://user-images.githubusercontent.com/19564426/188092599-05384e16-3e5a-47f8-a639-81231c8be0e8.jpg)

**The relighting results:**
![temp](https://user-images.githubusercontent.com/19564426/188093842-71c9411e-717e-4c7d-b4ca-53f467847b66.png)

2. In section 3.5 of the paper it is introduced that the purpose of **Rendering Networks** is to estimate the lighting of each input image and the material properties of the object, but the `self.env_lights` in class NeROICRenderer keeps the value unchanged since the initialization. I am curious about how to the network learning the various illumination conditions?

**Comment by zfkuang** [comment]
Hi Menpinland,
1. Good question! Thanks for pointing this out. The main reason why our model does not produce quite good relighting in this case is that our model are based on low level spherical-harmonics, which is designed to render images with very ambient lightings. Since you are using a lighting map with a very strong source (the sun), it will drasically affect the approximation from the SHs, and thus causing the artifact. An easy solution to that is to replace the SH-based rendering to other methods, such as SG-based rendering or just brute-force, and there're many resources you can look into. In the meantime, you can also try with some more ambient lighting, such as a cloudy outdoor scene, or an indoor scene with ambient lights.
2. I'm not quite sure what's the question here. The self.env_lights is used during the rendering at [here](https://github.com/snap-research/NeROIC/blob/ad19cad21a91864501910c92d984833baca6918a/models/neroic_renderer.py#L513) and thus trained with the back-propagated gradients. Let me know if this answers your question.

**Comment by Menpinland** [comment]
> Hi Menpinland,
> 
> 1. Good question! Thanks for pointing this out. The main reason why our model does not produce quite good relighting in this case is that our model are based on low level spherical-harmonics, which is designed to render images with very ambient lightings. Since you are using a lighting map with a very strong source (the sun), it will drasically affect the approximation from the SHs, and thus causing the artifact. An easy solution to that is to replace the SH-based rendering to other methods, such as SG-based rendering or just brute-force, and there're many resources you can look into. In the meantime, you can also try with some more ambient lighting, such as a cloudy outdoor scene, or an indoor scene with ambient lights.
> 2. I'm not quite sure what's the question here. The self.env_lights is used during the rendering at [here](https://github.com/snap-research/NeROIC/blob/ad19cad21a91864501910c92d984833baca6918a/models/neroic_renderer.py#L513) and thus trained with the back-propagated gradients. Let me know if this answers your question.

Thank you for your answer. I will try to get familiar with more lighting models and make more attempts. For the 2rd problem, I have misunderstood some details in the paper and caused confusion.
